export default {
    type:4,//门店助手的type都是4
    page:20,
    report:1,//是否回执
    genderZn:{
        1:'男',
        2:'女'
    },
    gender:{
        'man':1,
        'women':2
    },
    //文章
    article:{
        sale:1,//销售公告
        display:2,//陈列公告
    },
    articleZn:{
        display:'陈列公告',//陈列公告
        sale:'销售公告'//销售公告
    },

    //消息类型
    noticeZn:{
        1:'待办通知',
        2:'动态通知',
        3:'公司公告'
    },
    notice:{
        todo:1,
        info:2,
        company:3
    },
    //用户状态
    userStatus:{
        'normal':1,
        'free':2,
        'inviting':3,
        'applying':4,
        'quit':5,
        'refuse':6
    },
    userStatusZn:{
        1:'正常',
        2:'未邀请',
        3:'邀请中待确认',
        4:'申请加入中',
        5:'离职',
        6:'被拒绝',
    },
//    门店状态
    //门店状态
    shopStatusZn:{
        1:'筹备中',
        2:'施工中',
        3:'营业中',
        4:'撤柜关闭',
        5:'重装关闭',
        6:'移位关闭',
    },
    shopStatus:{
        ready:1,
        processing:2,
        businessing:3,
        canceled:4,
        renovated:5,
        moved:6
    },
}
